### PR TITLE
FOGL-6180

### PR DESCRIPTION
**Pull request by Mohit04tomar**

### CODE REVIEW

**Comment by Mohit04tomar** [comment]
We have integrated Unit Tests on CI and ran the Jenkins Job.
Below is the link for the Unit Tests Report -->
http://jenkins.dianomic.com:8080/job/fledge-iot-plugins-tester/job/fledge-south-expression/view/change-requests/job/PR-20/1/

Note: unit tests were run against develop branch of the fledge repository.

**Comment by MarkRiddoch** [comment]
> We have integrated Unit Tests on CI and ran the Jenkins Job. Below is the link for the Unit Tests Report --> http://jenkins.dianomic.com:8080/job/fledge-iot-plugins-tester/job/fledge-south-expression/view/change-requests/job/PR-20/1/
> 
> Note: unit tests were run against develop branch of the fledge repository.

The tests are not failing, it is the test environment that is at fault - it is not building the tests.

**Review by MarkRiddoch — CHANGES_REQUESTED** [review]
The test is not building, there appears to be a problem with the build environment

**Comment by ashish-jabble** [comment]
@MarkRiddoch Tests are also failing on local environment as well. I have made some comparison to other C repos which has unit tests and find that in **FindFledge.cmake** file we need to add rapidjson include directory in FLEDGE_INCLUDE_DIRS.
```
$ git diff
diff --git a/FindFledge.cmake b/FindFledge.cmake
index bb102ed..de63b1c 100644
--- a/FindFledge.cmake
+++ b/FindFledge.cmake
@@ -43,6 +43,7 @@ if (FLEDGE_SRC)
                get_filename_component(_ITEM_PATH ${_ITEM} DIRECTORY)
                list(APPEND FLEDGE_INCLUDE_DIRS ${_ITEM_PATH})
        endforeach()
+       list(APPEND FLEDGE_INCLUDE_DIRS "${FLEDGE_SRC}/C/thirdparty/rapidjson/include")
        unset(INCLUDE_LIST CACHE)
 
        list(REMOVE_DUPLICATES FLEDGE_INCLUDE_DIRS)
```
With given patch I am able to execute unit tests at my local environment & all are **PASSED**.

**Review by MarkRiddoch — APPROVED** [review]

**Pull request merged**
